services:
  rails:
    image: ${DOCKER_IMAGE_NAME-terrastories}
    build:
      context: ./rails
    environment:
      DEFAULT_MAPBOX_TOKEN: ${MAPBOX_ACCESS_TOKEN-pk.ey}
      DEFAULT_MAPBOX_STYLE: ${MAPBOX_STYLE-mapbox://styles/mapbox/streets-v11}
    command: scripts/server
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    expose:
      - "3000"